# Generated by Django 5.1.1 on 2024-10-10 05:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_member_groups_member_is_active_member_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
