# Generated by Django 5.1.1 on 2024-10-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_meeting_meeting_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='department',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='department',
            new_name='department_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='position',
            new_name='position_name',
        ),
    ]
