# Generated by Django 5.1.1 on 2024-10-10 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_rename_department_meeting_department_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='department_name',
            new_name='department_code',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='position_name',
            new_name='position_code',
        ),
    ]
