# Generated by Django 5.1.1 on 2024-10-10 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_rename_department_name_meeting_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='department_code',
            field=models.ForeignKey(db_column='department_code', on_delete=django.db.models.deletion.CASCADE, to='meeting.department'),
        ),
    ]
