# Generated by Django 5.1.1 on 2024-10-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_rename_department_code_member_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='department',
            new_name='department_code',
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
