# Generated by Django 5.1.1 on 2024-10-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0009_rename_department_member_department_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
