# Generated by Django 5.1.1 on 2024-10-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0010_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
    ]
