# Generated by Django 5.1.1 on 2024-10-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0011_remove_member_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='department_code',
        ),
        migrations.RemoveField(
            model_name='member',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='member',
            name='position',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Meeting',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
