# Generated by Django 5.1.1 on 2024-10-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0013_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
