# Generated by Django 5.1.1 on 2024-10-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0015_remove_participant_is_host_meeting_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minutes',
            name='summary',
        ),
        migrations.AddField(
            model_name='meeting',
            name='summary',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
